namespace:
  name: "app"

metadata:
  name: "graphql-docs"
  
labels:
  env: "dev"
  cluster: "luxrobo"

image:
  tag: latest
  repository: 012634413971.dkr.ecr.ap-northeast-2.amazonaws.com/graphql_docs
  imagePullPolicy: Always
  imagePullSecrets: ap-northeast-2-ecr-registry

service:
  http: 80
  targetHttp: 9000

ingress:
  host: docs
  domain: luxrobo.com
  targetHttp: 80